# Config for GWM-RNN-Text
pretrained_model: bert-base-uncased
num_layers: 2
hidden_dim: 1024
structural_dim: 384
fusion_mode: gated
dropout: 0.2
learning_rate: 1e-4
batch_size: 1024
loss: infonce
num_epochs: 200
temperature: 0.07

data_dir: data-processed/WN18RR
output_dir: output/gwm
    
add_inverse: true
early_stopping: 5
eval_every: 1
    
device: cuda
seed: 42

text_cache_batch_size: 128
text_cache_encode_device: cpu
text_cache_store_device: cuda

eval_batch_size: 1024
candidate_batch_size: 1024

max_length: 512
max_relation_length: 128